#!/bin/sh

# pv - previewer for lf file manager.

case "$1" in
	*.pdf)		pdftotext "$1" -;;
	*.zip)		unzip -l "$1";;
	*.rar)		unrar l "$1";;
	*.tar.*)	tar -tf "$1";;
	*)		highlight -O ansi "$1" || cat "$1";;
esac

### END OF FILE
