#!/bin/sh

# xprofile - This file will run upon login to a graphical
# session via a DM. This file will also be sourced via
# startx/xinit.

# This file's true location is in ~/.config/xprofile and a
# link can exist to it at ~/.xprofile. If a DM is not used,
# the link can be removed to have a cleaner home directory.

su_remaps &		# Remap keys

su_setbg &		# Set the background

xcompmgr &		# xcompmgr for transparency

dunst &			# dunst for notifications

unclutter &		# Hide mouse cursor when it is inactive.

xset r rate 300 50 &	# Speed xrate up

slstatus &		# Run slstatus

toggle_tpad &   # Turn the touchpad off by default.

### END OF FILE
