#!/bin/sh

# su_remaps - This script will run on startup.
# Primarily it remaps the CapsLock key so it does
# nothing.

# Map CapsLock key to nothing
setxkbmap -option caps:none

# Finally, map the menu button to Right Super as well.
xmodmap -e 'keycode 135 = Super_R'

### END OF FILE
