#!/bin/sh

CACHE=/home/jesse/.cache/weather

update_data() {
    curl -s --retry 5 --max-time 5 --retry-delay 4 --retry-max-time 40 "wttr.in/Perth?format=1" > $CACHE
}

update_data || exit 1

### END OF FILE
